### PR TITLE
Feat/256 invite users to apply for a project

### PR DESCRIPTION
**Pull request by HaseebIqbal33**
https://www.loom.com/share/a4d54b40b30547bab1ef68bba585c8bb?sid=9d0429e3-a7d6-4cd1-8396-e55fb77a9b22

### CODE REVIEW

**Comment by zubairaltaf10** [comment]
image
once the invitation process gets completed and i now navigate back to **Invites Tab** i don't see the invite freelancer button. Is it like that? And what if i want to add other freelancer through this invites?

**Comment by zubairaltaf10** [comment]
I have invited a freelancer under application tab but see this one. 
freelancer details does show up in invites tab. is like that or Am i missing something?
image

**Comment by zubairaltaf10** [comment]
Except the above mentioned comments rest of it looks good and functionality is working.

**Comment by HaseebIqbal33** [comment]
> image once the invitation process gets completed and i now navigate back to **Invites Tab** i don't see the invite freelancer button. Is it like that? And what if i want to add other freelancer through this invites?

Invited Button will only show in /freelancer page. Here is the list of invited users.

**Comment by HaseebIqbal33** [comment]
> I have invited a freelancer under application tab but see this one. freelancer details does show up in invites tab. is like that or Am i missing something? image

Here only freelancers applications will show. Application of those freelancers who applied.

**Pull request merged**
