### PR TITLE
194 create cloudinary utility function

### PR DESCRIPTION
**Pull request by HaseebIqbal33**
Add Project Detail Page for both Desktop and Mobile Screens
Add Project Listing for Mobile View
Added Applications Listing for Mobile View
Fix Some File Upload Issues

### CODE REVIEW

**Comment by Alien4Hire** [comment]
Here are some notes on the current implementation

can we shift this over to align with the left of the table?
image

also, can we add some padding to the bottom of this screen?
image


the list of previous applications should not be full screen here. lets make it as wide as the grey bar, and handle it the same way it is on the list freelancers page
image


hires should also have the table centered under the dashboard bar, and it should be the width of the grey bar. also, the blue bar under hire doesn't look correctly centered

image


Same applies to invoice page with being centered on the page

image

**Comment by Alien4Hire** [comment]
Clicking projects here should take you to the "View All" projects mobile screen
image

image

**Comment by Alien4Hire** [comment]
This page should have the names of the hired employees, but is showing something else
image

**Comment by Alien4Hire** [comment]
Design on invoice mobile page doesnt match the figma:
image

**Comment by Alien4Hire** [comment]
Title of dashboard should say Project at the top, and then the name of the project as the sub title
image

**Comment by Alien4Hire** [comment]
I created a new project, and I am able to see that it was successfully created, and it shows up in the API response, but it doesn't show up on the projects dashboard page. Please take a look at this.

image

**Comment by Alien4Hire** [comment]
Tasklist page is now throwing an error on this PR

http://[localhost:3000/dashboard/tasklist](http://localhost:3000/dashboard/tasklist)

image

**Comment by Alien4Hire** [comment]
Check out this page: On the main branch, it looks and works like shown here, but on your branch it appears broken.

http://[localhost:3000/projects](http://localhost:3000/projects)

image

**Comment by Alien4Hire** [comment]
The create a project flows styling is broken on this branch also

image

**Comment by Alien4Hire** [comment]
This section on the dashboard page has also become broken from this PR
image

**Comment by HaseebIqbal33** [comment]
> Here are some notes on the current implementation
> 
> can we shift this over to align with the left of the table? image
> 
> also, can we add some padding to the bottom of this screen? image
> 
> the list of previous applications should not be full screen here. lets make it as wide as the grey bar, and handle it the same way it is on the list freelancers page image
> 
> hires should also have the table centered under the dashboard bar, and it should be the width of the grey bar. also, the blue bar under hire doesn't look correctly centered
> 
> image
> 
> Same applies to invoice page with being centered on the page
> 
> image

Fixed

**Comment by HaseebIqbal33** [comment]
> This section on the dashboard page has also become broken from this PR image

Fixed

**Comment by HaseebIqbal33** [comment]
> The create a project flows styling is broken on this branch also
> 
> image

Fixed

**Comment by HaseebIqbal33** [comment]
> Check out this page: On the main branch, it looks and works like shown here, but on your branch it appears broken.
> 
> http://[localhost:3000/projects](http://localhost:3000/projects)
> 
> image

Fixed

**Comment by HaseebIqbal33** [comment]
> Tasklist page is now throwing an error on this PR
> 
> http://[localhost:3000/dashboard/tasklist](http://localhost:3000/dashboard/tasklist)
> 
> image

Fixed

**Comment by HaseebIqbal33** [comment]
> > Here are some notes on the current implementation
> > can we shift this over to align with the left of the table? image
> > also, can we add some padding to the bottom of this screen? image
> > the list of previous applications should not be full screen here. lets make it as wide as the grey bar, and handle it the same way it is on the list freelancers page image
> > hires should also have the table centered under the dashboard bar, and it should be the width of the grey bar. also, the blue bar under hire doesn't look correctly centered
> > image
> > Same applies to invoice page with being centered on the page
> > image
> 
> Fixed

Fixed

**Comment by HaseebIqbal33** [comment]
> This page should have the names of the hired employees, but is showing something else image

Fixed

**Comment by HaseebIqbal33** [comment]
> Here are some notes on the current implementation
> 
> can we shift this over to align with the left of the table? image
> 
> also, can we add some padding to the bottom of this screen? image
> 
> the list of previous applications should not be full screen here. lets make it as wide as the grey bar, and handle it the same way it is on the list freelancers page image
> 
> hires should also have the table centered under the dashboard bar, and it should be the width of the grey bar. also, the blue bar under hire doesn't look correctly centered
> 
> image
> 
> Same applies to invoice page with being centered on the page
> 
> image

Fixed

**Pull request merged**
