### PR TITLE
203 create employee withdrawal

### PR DESCRIPTION
**Pull request by zubairaltaf10**

### CODE REVIEW

**Comment by Alien4Hire** [comment]
@zubairaltaf10 Can you add loom video to this PR?

**Comment by zubairaltaf10** [comment]
> @zubairaltaf10 Can you add loom video to this PR?
[
Zoom link of current PR ](https://www.loom.com/share/f4cb9d3d52b34b848422cd41953ea45e)

**Comment by Alien4Hire** [comment]
The bank account is stored in stripe. You can see in staging that I have it set up to work already. We are not storing bank accounts in our system. Please review how it is done there currently and change this back to how it was. I actually had withdraw working without issue without this PR. 

image

Please reference the new section I added to this document explaining how selecting bank accounts works and how stripe keeps all information for them.

https://docs.google.com/document/d/1-ZyxDJVFudxRX7ZW39hULkem7NqH09TfLnjfbOcG88w/edit?usp=sharing

**Review by Alien4Hire — CHANGES_REQUESTED** [review]
Please review comments on how this will break existing withdraw features, and lets refactor this.

**Pull request closed without merging**
