### PR TITLE
Feat/209 update messaging flow for mobile and desktop

### PR DESCRIPTION
**Pull request by HaseebIqbal33**
Update Chat View According to New Figma
Added Chat Screen for Mobile View
Display Typing Animation
Refactor message query on server side
Fix Chat Unread 
https://www.loom.com/share/b41830e247fb469c8bd84738561c7d2c?sid=cf084f44-542b-47f8-b592-17d0c8f85ed9

### CODE REVIEW

**Comment by zubairaltaf10** [comment]
When user has an unread message there is an issue with the styling of a notification badge color like **2 unread messages** its not being shown properly. Can you please fix this one
image

**Comment by zubairaltaf10** [comment]
And this one too.**AM/PM** is not being properly rendered.
image

**Comment by zubairaltaf10** [comment]
There is an issue with the messaging flow on the mobile view. I have to refresh the page in order to get that notification icon like in the below image it is display **1 unread message**. Can you please take a look in this one.
image

**Comment by Alien4Hire** [comment]
I am getting issue where messages will not load on local. I have socket set up in env. Is there any additional setup I need to do?

image

**Pull request merged**
